twig:
    file_name_pattern: '*.twig'
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
        # the value is the service's id
        appCurrency: '@App\Service\PriceDisplayer'

when@test:
    twig:
        strict_variables: true
